lytics_site/lytics_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lytics_tables.urls')),
    # path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

lytics_site/lytics_tables/urls.py
from django.urls import path

from . import views

app_name = 'lytics'
urlpatterns = [
    path('', views.index, name='index'),
    path('lytics/', views.lytics, name='lytics'),
    path('lytics/streamer/<str:name>/', views.channelOverview, name='overview'),
    path('lytics/streamer/<str:name>/channel/', views.channelData, name='channel'),
    path('lytics/streamer/<str:name>/clips/', views.channelSlugs, name='clips'),
    path('lytics/custom_query/<str:source>/<str:query>/', views.customQuery, name='customQuery'),
    path('lytics/all_channels/', views.channelData_overview, name='channels_overview'),
    path('lytics/all_clips/', views.channelSlugs_overview, name='clips_overview'),
    path('shuttle/', views.shuttle, name='shuttle'),
    path('shuttle/demo/', views.shuttleDemoResults, name='shuttle_demo'),

]

lytics_site/lytics_tables/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Channels(models.Model):
    name = models.CharField(primary_key=True, max_length=25)
    sid = models.CharField(unique=True, max_length=20)
    bType = models.CharField(max_length=10)

    class Meta:
        managed = False
        db_table = 'channels'

    def __str__(self):
        output = self.name
        return output

class ChannelData(models.Model):
    name = models.ForeignKey('Channels', models.DO_NOTHING, db_column='name')
    game = models.CharField(max_length=40)
    views = models.BigIntegerField()
    followers = models.BigIntegerField()
    datetimeupdated = models.DateTimeField(db_column='dateTimeUpdated')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'channel_data'

    def __str__(self):
        output2 = str(self.views) + " " + self.game + " " + str(self.views)
        return output2

class SlugsData(models.Model):
    name = models.ForeignKey(Channels, models.DO_NOTHING, db_column='name')
    title = models.CharField(max_length=100)
    clip = models.CharField(max_length=50)
    views = models.BigIntegerField()
    datetimecreated = models.DateTimeField(db_column='dateTimeCreated')  # Field name made lowercase.
    timestamp_updated = models.DateTimeField(blank=True, null=True)


    class Meta:
        managed = False
        db_table = 'slugs_data'
    
    def __str__(self):
        return self.name

# Take note that django handles camelcase fields to lower case
# while raw queries are case sensitive

lytics_site/lytics_tables/forms.py
from django import forms
from django.forms import formset_factory

class ChannelForm(forms.Form):
    the_channel = forms.CharField(label='channel', max_length=30)

class CustomQueryForm(forms.Form):
    custom_query = forms.CharField(label='sql', max_length=200)

class AddressForm(forms.Form):
    name = forms.CharField(
        label='Address Please',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter Address address here please'
        })
    )

AddressFormset = formset_factory(AddressForm, extra=1)

lytics_site/lytics_tables/views.py
from django.shortcuts import render, get_list_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import loader
from django.urls import reverse
from django.db import connection
from collections import namedtuple

from .models import Channels, ChannelData, SlugsData
from .forms import ChannelForm, CustomQueryForm, AddressFormset
import subprocess


# TODO:j include ddt on docker image

# Create your views here.
def index(request):
    return render(request, 'lytics_tables/index.html',{})
    # return HttpResponse("Hello, this is the homepage")

def lytics(request):
    if request.method == 'GET':
        print('GET occured')

        if 'the_channel' in request.GET:
            print('the_channel')
            channelForm = ChannelForm(request.GET)
            if channelForm.is_valid():
                print('Form is valid')
                chan = channelForm.cleaned_data['the_channel']

                return HttpResponseRedirect(reverse('lytics:overview', args=(chan,)))
        
        # elif 'custom_query' in request.GET:
        #     print('custom_query')
        #     queryForm = CustomQueryForm(request.GET)

        #     if queryForm.is_valid():
        #         print('Form is valid')
        #         query = queryForm.cleaned_data['custom_query']

        #         return HttpResponseRedirect(reverse('lytics:customQuery', args=('customQueryGeneral', query)))

        else:
            print('Invalid form')
    

    channelForm = ChannelForm()
    # queryForm = CustomQueryForm()

    table = Channels.objects.all()
    context = {'table': table,
        'channelForm': channelForm,
        # 'queryForm': queryForm,
    }

    return render(request, 'lytics_tables/lytics.html', context)

def channelData(request, name):
    # data = ChannelData.objects.filter(name=name)
    print('The name is', name)
    data = ChannelData.objects.select_related('name').filter(name=name)
    context = {'channel': data}

    if not data:
        print('does not exist')
        context.update({'unfound_channel': name})
        # return Http404(name + ' is not within the database')

    # data = get_object_or_404(ChannelData, name=name)
    return render(request, 'lytics_tables/data.html', context)


def channelSlugs(request, name):
    data = SlugsData.objects.select_related('name').filter(name=name)
    context = {'channel': data}

    if not data:
        print('does not exist')
        context.update({'unfound_channel': name})

    return render(request, 'lytics_tables/slugs.html', context)

def channelOverview(request, name):
    print('channel overview')
    generalData = ChannelData.objects.select_related('name').filter(name=name)
    clipData = SlugsData.objects.select_related('name').filter(name=name)

    context = {
        'general': generalData,
        'clips': clipData
    }

    if not generalData:
        print('does not exist')
        context.update({'unfound_channel': name})

    return render(request, 'lytics_tables/overview.html', context)

def customQuery(request, query, source):
    print('Custom Query function is being used')

    # raw queries are not good enough. they are bound by primary keys
    with connection.cursor() as cursor:
        cursor.execute(query)
        queryResult = dictfetchall(cursor)

        # print(queryResult)
    # queryResult = Channels.objects.raw(query)
    # print(queryResult)
# 
    # print(queryResult[0][0])

    context = {
        source : queryResult,
        'userQuery': query,
    }

    return render(request, 'lytics_tables/customQuery.html', context)

    # can not use get_list_or_404 due to this being a raw query
    # try:
    #     queryResult = Channels.objects.raw(query)
    #     print(queryResult)

    #     context = {
    #         'customQuery': queryResult
    #     }

    #     return render(request, 'lytics_tables/customQuery.html', context)

    # except:
    #     raise Http404('Invalid query')
        # instead of raising this create a 404 page to be more descriptive

    # queryResult = get_list_or_404(queryResult)




def channelData_overview(request):
    # if request.method == 'GET':
    #     print('GET occured')

    #     if 'custom_query' in request.GET:
    #         print('custom_query')
    #         queryForm = CustomQueryForm(request.GET)

    #         if queryForm.is_valid():
    #             print('Form is valid')
    #             query = queryForm.cleaned_data['custom_query']

    #             return HttpResponseRedirect(reverse('lytics:customQuery', args=('customQueryData', query)))

    data = ChannelData.objects.select_related('name')
    context = {'channel': data}

    return render(request,'lytics_tables/data.html', context)

def channelSlugs_overview(request):
    # if request.method == 'GET':
    #     print('GET occured')

    #     if 'custom_query' in request.GET:
    #         print('custom_query')
    #         queryForm = CustomQueryForm(request.GET)

    #         if queryForm.is_valid():
    #             print('Form is valid')
    #             query = queryForm.cleaned_data['custom_query']

    #             return HttpResponseRedirect(reverse('lytics:customQuery', args=('customQueryClips', query)))

    data = SlugsData.objects.select_related('name')
    context = {'channel': data}

    return render(request,'lytics_tables/slugs.html', context)

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def shuttle(request):
    addrList = []
    if request.method == 'GET':
        formset = AddressFormset(request.GET or None)
    elif request.method == 'POST':
        formset = AddressFormset(request.POST)

        if formset.is_valid():

            tempFile = open("testFile.txt", "w")
            print(len(formset))
            print('print: ',formset[0].cleaned_data.get('name'))

            if len(formset) == 1 and formset[0].cleaned_data.get('name') is None:
                context = {
                    'emptyInput': True,
                }

                return render(request, 'lytics_tables/shuttleError.html', context)

            for form in formset:
                # extract name from each form and save
                name = form.cleaned_data.get('name')
                # print(name)
                if name is not None:
                    tempFile.write(name + "\n")
                    addrList.append(name)
                    
            print(addrList)

            tempFile.close()
            subprocess.call(["../../Shuttle/bin/shuttle", "read"])
            resultsFile = open("results.txt", "r")

            fileLines = resultsFile.readlines()
            pathHistory = []

            if fileLines[0] == 'error\n':
               errorAt = fileLines[1] 
               resultsFile.close()

               print(addrList[int(errorAt) - 1])

               context = {
                   'errorAt': addrList[int(errorAt) - 1],
               }

               return render(request, 'lytics_tables/shuttleError.html', context)

            else:
                maxAddresses = int(fileLines[0])

                for x in range(1, maxAddresses):
                    pathHistory.append(fileLines[x].replace("+", " "))

                duration = fileLines[maxAddresses + 1]
                miles = fileLines[maxAddresses + 2]

                print(pathHistory)
                print(duration)
                print(miles)

                resultsFile.close()

                context = {
                    'addresses': addrList,
                    'pathHistory': pathHistory,
                    'duration': duration,
                    'miles': miles,
                }

                return render(request, 'lytics_tables/shuttleResults.html', context)

    context = {
        'formset': formset,
    }

    # print(formset)

    return render(request, 'lytics_tables/shuttle.html', context)

def shuttleDemoResults(request, context):
    print('Hi')

    print(context['addresses'])


    return render(request, 'lytics_tables/shuttleResult.html', context)

lytics_site/lytics_tables/templates/lytics_tables/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta content="text/html">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'lytics_tables/lytics.css' %}">

    <title>{% block title %} My amazing site  {% endblock %}</title>
</head>

<body>
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'lytics:index' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'lytics:lytics' %}">Lytics</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'lytics:channels_overview' %}">Channel Overview</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'lytics:clips_overview' %}">Clips Overview</a>
                </li>
            </ul>
        </div>
    </nav>
    {% endblock %}
    {% block content %}
    {% endblock %}

    <!-- <section class="footer">
        <footer class="classFooter text-center">
            <h5>Developed by Jonathan using Django and Bootstrap</h5>
        </footer>
    </section> -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'lytics_tables/js/footer-reveal.min.js' %}"></script>
<script type="text/javascript" src="{% static 'lytics_tables/js/lytics.js' %}"></script>
</body>
</html>

lytics_site/lytics_tables/templates/lytics_tables/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta content="txt/html">
    <meta charset="utf-8">
    <title>Jerrerah</title>
    <meta name="description" content="My website"

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,600' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" type="text/css" href="{% static 'lytics_tables/style.css' %}">
    <link rel="stylesheet" href="{% static 'lytics_tables/skeleton.css' %}">
    <link rel="stylesheet" href="{% static 'lytics_tables/normalize.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'lytics_tables/fontawesome.css' %}"> -->

    <link rel="icon" type="image/png" href="{% static 'lytics_tables/images/favicon.png' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">


</head>

<body>
    <nav class="navigation">
        <a href="#" class="menu-icon">
            <i class="fa fa-bars"></i>
        </a>
        <ul class="main-navigation">
            <li><a href="#hero">Home</a></li> <!--hero-->
            <li><a href="#introduction">Introduction</a></li> <!--intro-->
            <li><a href="#interest">Interest</a></li> <!--creativity-->
            <li><a href="#projects">Projects</a></li> <!--work-->
            <li><a href="#contact">Contacts</a></li> <!--get in touch-->
            <li><a href="#about">About</a></li> <!--about us-->
        </ul>
    </nav>

    <section id="hero" class="hero u-full-width">
        <div class="hero-image"></div>
        <div class="container centeredHero">
            <div class="twelve columns">
                <h1 class="separator">Jonathan Herrera</h1>
                <h2>Software engineer driven by curiosity</h2>
            </div>
        </div>
    </section>

    <section id="introduction" class="introduction u-full-width">
        <div class="container">
            <div class="row">
                <div class="twelve columns">
                    <h3 class="separator">Introduction</h3>
                    <h4>I am a C/C++ and Python developer that is always looking forward to learning new things. 
                        The following are new technologies that I am really glad to have acquired recently.
                    </h4>
                </div>
                <ul class="u-full-width fa-5x adj">
                    <a href="https://docker.com">
                        <i class="fab fa-docker contactIcons my-icon"></i></a>
                    <a href="https://jenkins.io/">
                        <i class="fab fa-jenkins contactIcons"></i></a>
                    <a href="https://github.com/abseil/googletest">
                        <i class="fab fa-google contactIcons"></i></a>
                    <a href="https://www.djangoproject.com/">
                        <i class="fab fa-python contactIcons"></i></a>
                </ul>
            </div>
        </div>
    </section>
    
    <section id="interest" class="interest u-full-width featured-bg-image">
        <h4 class="centered">
            <button class="button inverted">Check out my projects</button>
        </h4>
    </section>

    <section id="projects" class="projects u-full-width">
        <div class="container">
            <div class="row">
                <div class="twelve columns">
                    <h3 class="separator">Projects</h3>
                </div>
            </div>
            <div class="row">
                <ul class="work-filters u-full-width">
                    <li class="active">
                        <a href="https://github.com/jherr029/twitch-clips-analytics">Lytics</a>
                    </li>
                    <li>
                        <a href="{% url 'lytics:lytics' %}">Lytics Alpha</a>
                    </li>
                    <li>
                        <a href="https://github.com/jherr029/Graphing-Calculator">Calculator</a>
                    </li>
                    <li>
                        <a href="https://www.youtube.com/watch?v=TZeS5Vxri7U">Dodger</a>
                    </li>
                    <li>
                        <a href="https://github.com/jherr029/pattern-check">Patterns</a>
                    </li>
                    <li>
                        <a href="{% url 'lytics:shuttle' %}">Shuttle</a>
                    </li>
                    <li>
                        <a href="https://www.youtube.com/watch?v=lAhPIHusmWA">Synth</a>
                    </li>
                </ul>
            </div>
            <div class="row">
                <ul class="work-items isotope">
                    <li class="four columns isotope-item">
                        <img src="https://www.twitch.tv/p/assets/uploads/combologo_474x356.png" class="twitch">
                        <div class="work-detail">
                            <div class="vertical-centered">
                                <h3>Lytics</h3>
                                <p class="separator orange">Twitch Clips Analysis</p>
                                <p>C++ and Mysql</p>
                                <p>In Alpha Stage</p>
                            </div>
                        </div>
                    </li>
                    <li class="four columns isotope-item">
                        <img src="https://images.unsplash.com/photo-1511377107391-116a9d5d20b5?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=c36af8fdc0ecb730540a3d1b9fef34f1&auto=format&fit=crop&w=2250&q=80" class="calc">
                        <div class="work-detail">
                            <div class="vertical-centered">
                                <h3>Android Graphing Calculator</h3>
                                <p class="separator orange">Based on Desmos Calculator</p>
                                <p>Java and Firebase</p>
                            </div>
                        </div>
                    </li>
                    <li class="four columns isotope-item">
                        <img src="{% static 'lytics_tables/images/work/dodge.png' %}" class="dodge">
                        <div class="work-detail">
                            <div class="vertical-centered">
                                <h3>Dodging Game</h3>
                                <p class="separator orange">Embedded System</p>
                                <p>C</p>
                            </div>
                        </div>
                    </li>
                    <li class="four columns isotope-item">
                        <img src="https://images.unsplash.com/reserve/uZYSV4nuQeyq64azfVIn_15130980706_64134efc6e_o.jpg?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=e13dac6ddcf9a4071422202015ae94a9&auto=format&fit=crop&w=2247&q=80" class="pattern">
                        <div class="work-detail">
                            <div class="vertical-centered">
                                <h3>Pattern Finder</h3>
                                <p class="separator orange">Parses a file to find valid patterns</p>
                                <p>C++</p>
                            </div>
                        </div>
                    </li>
                    <li class="four columns isotope-item">
                        <img src="https://images.unsplash.com/photo-1535655685871-dc8158ff167e?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=56f088e356da62acb6c8f0580fd106df&auto=format&fit=crop&w=1300&q=80" class="shuttle">
                        <div class="work-detail">
                            <div class="vertical-centered">
                                <h3>UCR Shuttle</h3>
                                <p class="separator orange">Traveling Salesman</p>
                                <p>C++ & Django</p>
                                <p>Gets the best route to travel all requested locations</p>
                            </div>
                        </div>
                    </li>
                    <li class="four columns isotope-item">
                        <img src="{% static 'lytics_tables/images/work/synth.jpg' %}">
                        <div class="work-detail">
                            <div class="vertical-centered">
                                <h3>Synthesizer</h3>
                                <p class="separator orange">Embedded System synthesizer</p>
                                <p>C, Atmega1284, Adruino Uno, and Raspberry Pi</p>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            <h1>
                Feel free to check out more information on my projects by clicking on the projects overview bar
            </h1>
        </div>
    </section>

    <section id="contact" class="contact u-full-width">
        <div class="container">
            <div class="row">
                <div class="twelve columns">
                    <h3 class="separator">Get in touch</h3>
                </div>
            </div>
            <ul class="u-full-width fa-6x">
                <a href="https://github.com/jherr029">
                    <i class="fab fa-github contactIcons"></i></a>
                <a href="https://www.linkedin.com/in/jonathan-herrera-52b22613b/">
                    <i class="fab fa-linkedin contactIcons"></i></a>
                <a href="mailto: jherreraj135@gmail.com">
                    <i class="fas fa-envelope contactIcons"></i></a>
                <a href="https://drive.google.com/file/d/1WymsS4zSBp-wzo8fIBC_rU2yrzxZkPny/view?usp=sharing">
                    <i class="fas fa-file-alt contactIcons"></i></a>
            </ul>
            </div>
        </div>
    </section>

    <section id="about" class="about u-full-width">
        <div class="container">
            <div class="row">
                <div class="twelve columns">
                    <h3 class="separator">About me</h3>
                    <h4>I graduated from University of California - Riverside with a BS in Computer Science in 2018.
                    I became who I am today due to my fascination with robots as a child. I enjoying reading, snowboarding
                    and making sure my dog is not making a mess.
                    </h4>
                </div>
            </div>
            <!-- <div class="row">
                <ul class="people-list">

                </ul>
            </div> -->
        </div>
    </section>

    <section class="footer u-full-width">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="twelve columns">
                        <h5>Developed by Jonathan using Django and Skeleton framework</h5>
                    </div>
                </div>
            </div>
        </footer>
    </section>

        <!-- Javascript
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>
    <script src="https://unpkg.com/scrollreveal"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.2/jquery.fancybox.min.js"></script>
    <script type="text/javascript" src="{% static 'lytics_tables/js/jquery.singlePageNav.min.js' %}"></script>
    <!-- <script type="text/javascript" src="{% static 'lytics_tables/js/footer-reveal.min.js' %}"></script> -->
    <script type="text/javascript" src="{% static 'lytics_tables/js/scripts.js' %}"></script>

</body>
</html>

lytics_site/lytics_tables/templates/lytics_tables/shuttle.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
</head>
    <meta content="text/html">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'lytics_tables/lytics.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">


<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'lytics:index' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"  aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'lytics:shuttle' %}">Shuttle</a>
                </li>
            </ul>
        </div>
    </nav>


    <section id="introduction">
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <h1>Shuttle app</h1>
                <p clas="lead">
                    This app aims to solves the classical traveling salesmans problem. UCR provides a program in which they shuttle students
                    to their requested destinations. The shuttle driver has to create a route based on all the requests provided by the students which
                    may lead to a nonoptimal route. The following is a small demo of the traveling salesman problem.
                </p>
                <hr class="my-4">
                <p>
                    Features in the development pipeline:
                </p>
                <div class="contianer">
                    <ul class="list-group">
                        <li class="list-group-item">User groups (admin, shuttle driver, students)</li>
                        <li class="list-group-item">Database</li>
                        <li class="list-group-item">Analytics</li>
                        <li class="list-group-item">Heatmap</li>
                        <li class="list-group-item">Map Integration</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <div class="container">
        <form class="form-horizontal" method="POST" action="">
            {% csrf_token %}
            {{ formset.management_form }}
            {% for form in formset %}
            <div class="row form-row spacer">
                <div class="col-2">
                    <label>{{form.name.label}}</label>
                </div>
                <div class="col-4">
                    <div class="input-group">
                        {{form.name}}
                        <div class="input-group-append">
                            <button class="btn btn-success add-form-row">
                                <i class="fas fa-plus fa-xs"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="row spacer">
                <div class="col-4 offset-2 marginBot">
                    <button type="submit" class="btn submitBtn btn-block btn-primary" id="load" data-loading-text="<i class=fa fa-circle-o-notch fa-spin'></i>Calculating Route">
                        Submit
                    </button>
                </div>
            </div>
        </form>
    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <!-- <script type="text/javascript" src="{% static 'lytics_tables/js/footer-reveal.min.js' %}"></script> -->
    <script type="text/javascript" src="{% static 'lytics_tables/js/shuttle.js' %}"></script>
</body>    

</html>